---
services:
  app:
    image: ${IMAGE_UNDER_TEST:-alpine-php-webserver:test}
    build: .
  sut:
    image: alpine:3.23
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
